config/routes.rb
Www::Application.routes.draw do
  
  scope "(:locale)", :locale => /en|fr/ do
    
    match 'home'    => "static_pages#home",   :as => 'home',    :via => :get
    match 'admin'   => "static_pages#admin",  :as => 'admin',   :via => :get
    match 'mobile'  => "static_pages#mobile", :as => 'mobile',  :via => :get
    match 'faq'     => "static_pages#faq",    :as => 'faq',     :via => :get
    match 'contact' => 'contact#new',         :as => 'contact', :via => :get
    match 'contact' => 'contact#create',      :as => 'contact', :via => :post
    
    match 'all_aircrafts'      => 'aircrafts#all_aircrafts',            :as=>"all_aircrafts",       :via =>:get
    match 'all_models'         => 'models#all_models',                  :as=>"all_models",          :via =>:get
    match 'all_makers'         => 'makers#all_makers',                  :as=>"all_makers",          :via =>:get
    match 'all_station_types'  => 'station_types#all_station_types',    :as=>"all_station_types",   :via =>:get
    match 'all_fuel_locations' => 'fuel_locations#all_fuel_locations',  :as=>"all_fuel_locations",  :via =>:get
    match 'all_fuel_types'     => 'fuel_types#all_fuel_types',          :as=>"all_fuel_types",      :via =>:get
    
    resources :makers,          :except => [:index]
    resources :models,          :except => [:index]
    resources :envelopes,       :except => [:index]
    resources :fuel_types,      :except => [:show] 
    resources :fuel_locations,  :except => [:show]
    resources :station_types,   :except => [:show]
    
    devise_for :users
      
    resources :users do
      member do
        put :save_roles
        get :edit_roles
        get :profile
      end
    end
    
    resources :aircrafts do
      
      resources :aircraft_comments, :except =>[:index, :new]
      
      collection do 
        get :filter_models
        get :filter_aircrafts
      end
      
      member do 
        get :clone
        get :weight_balance
        get :fly  
        get :report    
      end 
      
    end
    
    resources :aircraft_comments, :except => [:new]
    
    root :to => "static_pages#home"
  end
  

end

app/controllers/static_pages_controller.rb
## Manage static pages
class StaticPagesController < ApplicationController

  def home
    respond_to do |format|
      format.html {render :layout => false} ## use custom layout for home page
    end
  end

  def admin
    authorize! :admin, :show
    respond_to do |format|
      format.html 
    end
  end
    
  def mobile
    respond_to do |format|
      format.html 
    end
  end
  
  def faq
    respond_to do |format|
      format.html
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/admin.html.erb
<!-- breadcrumb -->
<% content_for :breadcrumb do %>
  <%= link_to t(:home), home_path %>
  <%= t(:administration) %>
<% end %>

<!-- page information -->
<h4 class="header-line"><%= t(:administration) %></h4>
<p>
  <%= t(:admin_page_sub_title) %>
</p>
<br/>
<div class="clear "></div>

<div class="admin-option-small">
  <div class="pic">
    <%= image_tag "icons/suitcase.png" %>
  </div>
  <div class="admin-category">
    <%= link_to t(:cat_station_types), station_types_path %>
  </div>
  <br/>
  <div class="admin-desc">
    <p>
      <% StationType.limit(5).each do |station| %>
        <% if I18n.locale == :fr %>
          <%= station.fr %>, 
        <% else %>
          <%= station.en %>, 
        <% end %>
      <% end %>
      ...
     </p>
  </div> 
</div>

<div class="admin-option-small">
  <div class="pic">
    <%= image_tag "icons/gameplan.png" %>
  </div>
  <div class="admin-category">
    <%= link_to t(:cat_fuel_locations), fuel_locations_path %>
  </div>
  <br/>
  <div class="admin-desc">
    <p>
      <% FuelLocation.limit(5).each do |location| %>
        <% if I18n.locale == :fr %>
          <%= location.fr %>, 
        <% else %>
          <%= location.en %>,
        <% end %>
      <% end %>
      ...
     </p>
  </div> 
</div>

<div class="admin-option-small">
  <div class="pic">
    <%= image_tag "icons/fuel.png" %>
  </div>
  <div class="admin-category">
    <%= link_to t(:cat_fuel_types), fuel_types_path %>
  </div>
  <br/>
  <div class="admin-desc">
    <p>
      <% FuelType.limit(5).each do |fuel| %>
          <%= fuel.name %>, 
      <% end %>
      ...
     </p>
  </div> 
</div>

<div class="admin-option-small">
  <div class="pic">
    <%= image_tag "icons/group.png" %>
  </div>
  <div class="admin-category">
    <%= link_to t(:cat_users), users_path %>
  </div>
  <br/>
  <div class="admin-desc">
    <p><%= t(:cat_users_info) %></p>
  </div> 
</div>

<div class="admin-option-small">
  <div class="pic">
    <%= image_tag "icons/chat.png" %>
  </div>
  <div class="admin-category">
    <%= link_to t(:cat_comments), aircraft_comments_path %> 
  </div>
  <br/>
  <div class="admin-desc">
    <p><%= t(:cat_comments_info) %></p>
  </div> 
</div>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Weight & Balance</title>
  <%= stylesheet_link_tag "application", "ridge", :media => "all" %>
  <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Ubuntu" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="home">

<!-- WRAPPER -->
	<div id="wrapper">
		
		<!-- HEADER -->
		<div id="header">
			<a href="index.html"><div id="logo"><%= image_tag "logo.png", :alt=>"HOME" %></div></a>
			<!-- i18n -->
			<div id="i18n-holder">
				<ul class="i18n">
				  <li><%= link_to "", build_locale_url('en'), :class => "uk" %></li>
				  <li><%= link_to "", build_locale_url('fr'), :class => "fr" %></li>
				</ul>
			</div>
			<!-- ENDS i18n -->
			
			
			<!-- Navigation -->
			<ul id="nav" class="sf-menu">
				<li><%= link_to t(:home).upcase, home_path %></a></li>
				
				<!-- redirect to sign in page if user is not logged -->
				<% if user_signed_in? %>
  				<li><%= link_to t(:my_account).upcase, user_path(current_user.id)%></a></li>
  		  <% else %>
  		    <li><%= link_to t(:my_account).upcase, new_user_session_path %></a></li>
  		  <% end %>
  		  
				<li><%= link_to t(:aircrafts).upcase, aircrafts_path %></a></li>
				<li><%= link_to t(:mobile).upcase, mobile_path %></a></li>
				<li><%= link_to t(:contact).upcase, contact_path %></a></li>
				
				<% if user_signed_in? && current_user.has_role?(:admin) %>
				  <li><%= link_to "ADMINISTRATION", admin_path %></a></li>
				<% end %>
				
			</ul>
			<!-- Navigation -->	
			
			<!-- search -->
			<div class="top-search">
		    <%= form_tag aircrafts_path, :id=>"searchform", :method => 'get' do %>
          <div>
            <%= text_field_tag :search, params[:search], :id=>"s", :value=>"call sign" %>
            <%= submit_tag "", :name => nil, :id=>"searchsubmit" %>
          </div>
        <% end %>
			</div>
			<!-- ENDS search -->
			
			<!-- headline -->
				<div id="headline">
					<%= t(:main_title).html_safe %>
					<%= link_to t(:main_title_download), mobile_path %>
				</div>
				<!-- ENDS headline -->
				
				<!-- Slider -->
        
        <center>
  			<div id="slider-block">
  				<div id="slider-holder">
  						<%= image_tag "main-image.png" %>
  				</div>
  			</div>
  			</center>
  		

			<!-- ENDS Slider -->

		</div>
		<!-- ENDS HEADER -->
		
		<!-- MAIN -->
		<div id="main">
			
			<!-- content -->
			<div id="content">
				
				<!-- page-content -->
				<div id="page-content">
          
          
          <div class="one-half">
            <br/>
            <h6><i>Weight & Balance</i> has been built from the ground up to quickly and accurately provide weight and balance calculations for nearly any general aviation aircraft</h6>
          </div>
          
          <div class="one-half last">
          
          <h1>Features</h1>
            <br/>
            <ul>
              <li><%= image_tag "bullets/check.png"%> Create and customize nearly any aircraft's characteristics</li>
              <li><%= image_tag "bullets/check.png"%> Browse our ever expending aircraft catalog</li>
              <li><%= image_tag "bullets/check.png"%> Fast and accurate weight and balance calculations</li>
              <li><%= image_tag "bullets/check.png"%> Switch between metric and US unit system</li>
              <li><%= image_tag "bullets/check.png"%> Use Weight & Balance on your iPad</li>
              <li>...</li>
            </ul>
          </div>

        </div>
				<!-- ENDS page-content -->
			</div>
			<!-- ENDS content -->
		</div>
		<!-- ENDS MAIN -->
		
		<!-- FOOTER -->
		<div id="footer">
			
			<!-- footer-cols -->
			<ul id="footer-cols">
				<li class="col">
					<h6><%= t(:about) %></h6>
					<%= t(:text_about).html_safe %> (<%= link_to "HEIG-VD", "http://www.heig-vd.ch", :class=>"yellow-link" %>).
				</li>
				<li class="col">
					<h6><%= t(:navigate) %></h6>
					<ul>
						<li><%= link_to t(:home), home_path %></a></li>
				
    				<!-- redirect to sign in page if user is not logged -->
		    		<% if user_signed_in? %>
  			     	<li><%= link_to t(:my_account), user_path(current_user.id)%></a></li>
      		  <% else %>
  	     	    <li><%= link_to t(:my_account), new_user_session_path %></a></li>
      		  <% end %>
  		  
		    		<li><%= link_to t(:aircrafts), aircrafts_path %></a></li>
    				<li><%= link_to t(:contact), contact_path %></a></li>				
					</ul>
				</li>
				<li class="col">
					<h6><%= t(:tools) %></h6>
					<ul>
  					<li><%= link_to t(:mobile), mobile_path %></a></li>
					</ul>
				</li>
			</ul>
			<!-- ENDS footer-cols -->
			
			<!-- Bottom -->
			<div id="bottom">
				2012 - <a href="http://www.heig-vd.ch"> Heig-vd</a> - Blanc

			</div>
			<!-- ENDS Bottom -->
		</div>
		<!-- ENDS FOOTER -->
	</div>
	<!-- ENDS WRAPPER -->


</body>
</html>