config/routes.rb
Www::Application.routes.draw do
  
  scope "(:locale)", :locale => /en|fr/ do
    
    match 'home'    => "static_pages#home",   :as => 'home',    :via => :get
    match 'admin'   => "static_pages#admin",  :as => 'admin',   :via => :get
    match 'mobile'  => "static_pages#mobile", :as => 'mobile',  :via => :get
    match 'faq'     => "static_pages#faq",    :as => 'faq',     :via => :get
    match 'contact' => 'contact#new',         :as => 'contact', :via => :get
    match 'contact' => 'contact#create',      :as => 'contact', :via => :post
    
    match 'all_aircrafts'      => 'aircrafts#all_aircrafts',            :as=>"all_aircrafts",       :via =>:get
    match 'all_models'         => 'models#all_models',                  :as=>"all_models",          :via =>:get
    match 'all_makers'         => 'makers#all_makers',                  :as=>"all_makers",          :via =>:get
    match 'all_station_types'  => 'station_types#all_station_types',    :as=>"all_station_types",   :via =>:get
    match 'all_fuel_locations' => 'fuel_locations#all_fuel_locations',  :as=>"all_fuel_locations",  :via =>:get
    match 'all_fuel_types'     => 'fuel_types#all_fuel_types',          :as=>"all_fuel_types",      :via =>:get
    
    resources :makers,          :except => [:index]
    resources :models,          :except => [:index]
    resources :envelopes,       :except => [:index]
    resources :fuel_types,      :except => [:show] 
    resources :fuel_locations,  :except => [:show]
    resources :station_types,   :except => [:show]
    
    devise_for :users
      
    resources :users do
      member do
        put :save_roles
        get :edit_roles
        get :profile
      end
    end
    
    resources :aircrafts do
      
      resources :aircraft_comments, :except =>[:index, :new]
      
      collection do 
        get :filter_models
        get :filter_aircrafts
      end
      
      member do 
        get :clone
        get :weight_balance
        get :fly  
        get :report    
      end 
      
    end
    
    resources :aircraft_comments, :except => [:new]
    
    root :to => "static_pages#home"
  end
  

end

app/models/aircraft.rb
class Aircraft < ActiveRecord::Base
    
  LBS_TO_KG = 0.45359237
  INCH_TO_M = 0.0254
  GAL_TO_L = 3.78541178
  
  ## determines whether the aircraft has to be normalized or not (converted to metric)
  attr_accessor :normalize
  
  ## associations
  belongs_to  :model
  has_one     :envelope,          :dependent => :destroy
  has_many    :stations,          :dependent => :destroy
  has_many    :fuel_tanks,        :dependent => :destroy
  has_many    :aircraft_comments, :dependent => :destroy
  
  ## validations
  validates_presence_of :callSign, :emptyWeight, :emptyArm, :mtow, :mldgw
  validates_uniqueness_of :callSign
  validates_associated :model
  validate :validate_stations_count, :validate_fuel_tanks_count
  before_save :normalize_aircraft
  
  
  ## image
  has_attached_file :image, 
                    :url => '/system/:class/:attachment/:id/:style/:filename',
                    :styles => {:tiny   => ["75x75#",   :png],
                                :thumb  => ["100x100#", :png], 
					                      :small  => ["150x150>", :png],  
                					      :medium => ["300x300>", :png], 
                                :large  => ["500x500>", :png]},
                    :default_url => 'no-image/:style/no-image.gif'
  
  ## nested attributes -> stations + fuel tanks
  accepts_nested_attributes_for :stations, :reject_if => lambda { |a| a[:arm].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :fuel_tanks, :reject_if => lambda { |a| a[:arm].blank? }, :allow_destroy => true
  
  ## duplicates current aircraft
  def duplicate
    craft = Aircraft.new
    craft = self.dup :include => [:stations, :fuel_tanks, :envelope]    
    craft.callSign = ""
        
    return craft
  end
  
  ## validates the number of stations
  def validate_stations_count
    if self.stations.length < 1
      errors.add(:base, 'At least one station for pilot seat!')
    end
    
    ## check for stations marked for destruction
    to_be_deleted = 0
    
    self.stations.each do |station|
      if station.marked_for_destruction?
        to_be_deleted += 1
      end
    end
    
    if to_be_deleted == self.stations.length
      errors.add(:base, 'At least one station for pilot seat')
    end
    
    return true
  end
  
  ## validates the number of fuel tanks
  def validate_fuel_tanks_count
    if self.fuel_tanks.length < 1
      errors.add(:base, 'At least one fuel tank!')
    end
    
    ## check for fuel tanks marked for destruction
    to_be_deleted = 0
    
    self.fuel_tanks.each do |tank|
      if tank.marked_for_destruction?
        to_be_deleted += 1
      end
    end
    
    if to_be_deleted == self.fuel_tanks.length
      errors.add(:base, 'At least one fuel tank!')
    end
    
    return true
  end
  
  ## converts all units to metric
  def normalize_aircraft
    if self.normalize
      
      self.emptyWeight  *= LBS_TO_KG
      self.emptyArm     *= INCH_TO_M
      self.mtow         *= LBS_TO_KG
      self.mldgw        *= LBS_TO_KG
      
      self.stations.each do |station|
        station.arm       *= INCH_TO_M
        station.weightMax *= LBS_TO_KG
      end
      
      self.fuel_tanks.each do |tank|
        tank.arm        *= INCH_TO_M
        tank.volumeMax  *= GAL_TO_L
      end
      
      self.normalize = false
      save!
    end
  end
  
end

app/controllers/aircrafts_controller.rb
class AircraftsController < ApplicationController
  
  ## constants used to convert units when 
  ## doing weight and balance
  KG_TO_LBS         = 2.20462262
  M_TO_INCH         = 39.3700787
  L_TO_GAL          = 0.264172052
  INCH_LBS_TO_M_KG  = 0.0559974146
  KG_L_TO_LBS_GAL   = 8.34540445
  
  before_filter :authenticate_user!, :except => [:index, :show, :filter_models, :filter_aircrafts, :weight_balance, :fly, :all_aircrafts]    
  
  ### REST API specific methods ##################################################
  
  ## REST API
  ## GET /all_aircrafts
  def all_aircrafts
    
    @aircrafts = Aircraft.all
    respond_to do |format|
      format.json{ render :json =>@aircrafts.to_json(
              :include => { :stations => {}, 
                            :fuel_tanks => {}, 
                            :envelope => {:include => :coordinates}
                          }
            )
        }
    end
  end
  
  
  ### HTML + JSON REST ##################################################
  
  ## GET /aircraft/:id/weight_balance
  ## user input for weight and balance
  def weight_balance
    @aircraft = Aircraft.find(params[:id])
    @stations = @aircraft.stations.find(:all, :include => "station_type", :order => "station_types.position")
    @fuel_tanks = @aircraft.fuel_tanks.find(:all, :include =>"fuel_location", :order=> "fuel_locations.position")
    @comments = @aircraft.aircraft_comments.order("created_at DESC").page(params[:page]).per(4)
    @comments_count = @aircraft.aircraft_comments.count
    
    respond_to do |format|
      format.html
    end
  end
  
  ## sends report by email
  def report
    render :nothing => true, :status => 200
    NotificationsMailer.report(current_user.email, session["report"]).deliver
    
  end
  
      
  ## GET /aircraft/:id/fly
  ## Return results for weight and balance
  def fly
    @aircraft = Aircraft.find(params[:id])
    @stations = @aircraft.stations.find(:all, :include => "station_type", :order => "station_types.position")
    @fuel_tanks = @aircraft.fuel_tanks.find(:all, :include =>"fuel_location", :order=> "fuel_locations.position")
    @comments = @aircraft.aircraft_comments.order("created_at DESC").page(params[:page]).per(4)
    @comments_count = @aircraft.aircraft_comments.count
    @envelope = @aircraft.envelope
    
    max_allowed_fuel_liters = Array.new
    to_fuel = Array.new
    ld_fuel = Array.new
    
    ## converts string params to float
    @weights = params[:weights].collect{|i| i.to_f}
    to_fuels = params[:tofuel].collect{|i| i.to_f}
    ld_fuels = params[:ldfuel].collect{|i| i.to_f}
    
    @x_max = @envelope.coordinates.order("cg ASC").maximum(:cg)
    @x_min = @envelope.coordinates.order("cg ASC").minimum(:cg)
    @y_max = @envelope.coordinates.order("weight ASC").maximum(:weight)
    @y_min = @envelope.coordinates.order("weight ASC").minimum(:weight)
    
    ## converts all values to metric for calculations
    @units = params[:units]
      
    ## converts all aircraft values if using us units
    if @units && @units == "us"
      @aircraft.emptyWeight *= KG_TO_LBS
      @aircraft.emptyArm *= M_TO_INCH
      @aircraft.mtow *= KG_TO_LBS
      @aircraft.mldgw *= KG_TO_LBS 
      @aircraft.model.fuel_type.density *= KG_L_TO_LBS_GAL
      
      @x_max *= M_TO_INCH
      @x_min *= M_TO_INCH
      @y_max *= KG_TO_LBS
      @y_min *= KG_TO_LBS
      
      @stations.each do |station|
        station.arm *= M_TO_INCH
        station.weightMax *= KG_TO_LBS
      end
      
      @fuel_tanks.each do |tank|
        tank.arm *= M_TO_INCH
        tank.volumeMax *= L_TO_GAL
      end
      
      @envelope.coordinates.each do |coord|
        coord.cg *= M_TO_INCH
        coord.weight *= KG_TO_LBS
      end    
    end
  
    max_allowed_fuel = max_allowed_fuel_liters(@fuel_tanks)
    
    ## sum calculations
    @to_weight = aircraft_weight(@weights, to_fuels)
    @ld_weight = aircraft_weight(@weights, ld_fuels)
    @to_cg = aircraft_moment(@weights, to_fuels) / @to_weight
    @ld_cg = aircraft_moment(@weights, ld_fuels) / @ld_weight
    @to_fuel = to_fuels.inject(0){|sum,item| sum + item}
    @ld_fuel = ld_fuels.inject(0){|sum,item| sum + item}
    
    ## error handling
    @errors = Hash.new
    @errors["to_weight"] = t(:mtow_out, :value=>@aircraft.mtow) if @to_weight > @aircraft.mtow
    @errors["ld_weight"] = t(:mldgw_out, :value=>@aircraft.mldgw) if @ld_weight > @aircraft.mldgw
    @errors["to_cg"]     = t(:to_cg_out) unless point_in_envelope?(@to_cg, @to_weight, @envelope.coordinates.sort_by{|t| t.order})
    @errors["ld_cg"]     = t(:ld_cg_out) unless point_in_envelope?(@ld_cg, @ld_weight, @envelope.coordinates.sort_by{|t| t.order})
    @errors["to_fuel"]   = t(:to_fuel) if @to_fuel == 0 || @to_fuel > max_allowed_fuel
    @errors["ld_fuel"]   = t(:ld_fuel) if @ld_fuel > @to_fuel || @ld_fuel <= 0 || @ld_fuel > max_allowed_fuel
    
    report = Report.new
    report.to_weight = @to_weight
    report.ld_weight = @ld_weight
    report.to_fuel = @to_fuel
    report.ld_fuel = @ld_fuel
    report.to_cg = @to_cg
    report.ld_cg = @ld_cg
    report.errors = @errors
    
    session["report"] = report
    
    respond_to do |format|
      format.html
    end
  end
  
  ## Filters models by maker and renders a list through jquery
  def filter_models
    @maker = Maker.find(params[:maker])
    @models = @maker.models.order("name ASC")
    
    respond_to do |format|
      format.js
    end
  end
  
  ## Filters aircrafts by models and renders a list through jquery
  def filter_aircrafts
    @model = Model.find(params[:model])
    @aircrafts = @model.aircrafts.order("callSign ASC")
    
    respond_to do |format|
      format.js
    end
  end
  
  ## Clones an existing aircraft and its envelope
  def clone
    @old_craft = Aircraft.find(params[:id])
    @model = @old_craft.model
    @aircraft = @old_craft.duplicate
    
    ## required for nested stations and fuel tanks
    @stationTypes = StationType.find(:all, :order=>:position)
    @fuelLocations = FuelLocation.all
    
    respond_to do |format|
      format.html
    end
  end
  
  # GET /aircrafts
  # GET /aircrafts.json
  def index
    search = params[:search]
    
    if search ## search by specific call sign
      @aircrafts = Aircraft.find(:all, :conditions => ['callSign LIKE ?', "%#{search}%"])
      
      ## get all models by aircrafts
      @models = Array.new
      @aircrafts.each do |craft|
        @models<< craft.model  
      end
      
      ## get all makers by models
      @makers = Array.new
      @models.each do |model|
        @makers << model.maker
      end
      
      ## remove duplicates
      @models = @models.uniq
      @makers = @makers.uniq
      
    else ## display all aircrafts, models and makers
      @makers = Maker.order("name ASC")
      @models = Model.order("name ASC")
      @aircrafts = Aircraft.order("callSign ASC")
    end    

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @aircrafts }
    end
  end
   
  # GET /aircrafts/1
  # GET /aircrafts/1.json
  def show
    @aircraft = Aircraft.find(params[:id])
    @model = @aircraft.model
    @stations = @aircraft.stations.find(:all, :include => "station_type", :order => "station_types.position")
    @fuel_tanks = @aircraft.fuel_tanks.find(:all, :include =>"fuel_location", :order=> "fuel_locations.position")
    @comments = @aircraft.aircraft_comments.order("created_at DESC").page(params[:page]).per(4)
    @comments_count = @aircraft.aircraft_comments.count
    @updated_by = User.find(@aircraft.updated_by)
    @created_by = User.find(@aircraft.created_by)
    @envelope = @aircraft.envelope
    
    ## min and max values used to draw the envelope
    ## this has to be here because the drawing method is shared
    ## with weight and balance action which can be done using us and 
    ## metric units
    if @envelope
      @x_max = @envelope.coordinates.order("cg ASC").maximum(:cg)
      @x_min = @envelope.coordinates.order("cg ASC").minimum(:cg)
      @y_max = @envelope.coordinates.order("weight ASC").maximum(:weight)
      @y_min = @envelope.coordinates.order("weight ASC").minimum(:weight)
    end
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => [@aircraft, @stations, @fuel_tanks, @aircraft.envelope.coordinates] }
    end
  end

  # GET /aircrafts/new
  # GET /aircrafts/new.json
  def new
    @aircraft = Aircraft.new
    @model = Model.find(params[:model])
    
    ## required for nested stations and fuel tanks
    @stationTypes = StationType.find(:all, :order=>:position)
    @fuelLocations = FuelLocation.all
    
    ## one default station for pilot seat
    station = @aircraft.stations.build
    
    ## at least one fuel tank
    fuelTank = @aircraft.fuel_tanks.build
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @aircraft }
    end
  end

  # GET /aircrafts/1/edit
  def edit
    @aircraft = Aircraft.find(params[:id])
    @model = @aircraft.model
    
    ## required for nested stations and fuel tanks
    @stationTypes = StationType.all
    @fuelLocations = FuelLocation.all
  end

  # POST /aircrafts
  # POST /aircrafts.json
  def create
    @aircraft = Aircraft.new(params[:aircraft])
    @model = @aircraft.model
    
    ## required for nested stations and fuel tanks
    @stationTypes = StationType.all
    @fuelLocations = FuelLocation.all
    
    ## aicraft was cloned
    cloned_from = params[:cloned_from]
    
    ## normalize characteristics if using us units
    unit = params[:units]
    @aircraft.normalize = true if (unit && unit == "us")
    
    ## created by user
    @aircraft.created_by = current_user.id
    @aircraft.updated_by = current_user.id
    
    respond_to do |format|
      ## cloning envelope if duplicating the aircraft
      if cloned_from && Aircraft.find(cloned_from).envelope
        envelope = Envelope.new

app/helpers/aircrafts_helper.rb
module AircraftsHelper
  
  DEFAULT_IMAGE_NAME = "no-image.gif"
  
  ## checks wether the current aircraft has a specific image or not
  def has_default_image
    return @aircraft.image.url.include? DEFAULT_IMAGE_NAME
  end
  
  ## gets the maximum capacity of fuel in liters
  def max_fuel_liters
    max = 0
    
    @fuel_tanks.each do |tank|
      max += tank.volumeMax
    end
    
    return max
  end
  
  ## gets the maximum capacity of fuel in kilograms
  def max_fuel_kilos
    return max_fuel_liters * @aircraft.model.fuel_type.density
  end
  
  ## gets the maximum mass of all stations in kilograms
  def max_stations_kilos
    max = 0
    
    @stations.each do |station|
      max += station.weightMax
    end
    
    return max
  end
  
end

app/views/aircrafts/_filtered_aircrafts.html.erb
<!-- displays models filtered by maker -->

<div class="options">
  <%= link_to image_tag("mono-icons/plus16.png"), new_aircraft_path(:model=>@model.id) %>  
</div>

<center>
  <h6><%= @model.name %></h6>
</center>
<br/>

<% if @model.aircrafts.count > 0 %>
  <% @aircrafts.each do |craft| %>
    <%= link_to (image_tag "mono-icons/risegraph16.png", :alt=>"Editer"), weight_balance_aircraft_path(:id =>craft.id) %> 
    <%= link_to craft.callSign, craft %>
    <br/>
  <% end %>
<% else %>
  <center>
    <%= image_tag "mono-icons/warning16.png" %> 
    <%= t(:no_aircraft_found) %>
  </center>
<% end %>

app/views/aircrafts/_filtered_models.html.erb
<!-- displays models filtered by maker -->

<div class="options">
  <%= link_to image_tag("mono-icons/plus16.png"), new_model_path(:maker=>@maker.id) %>  
</div>


<center>
  <h6><%= @maker.name %></h6>
</center>
<br/>

<% if @models.count > 0 %>
  <% @models.each do |model| %>
    <%= link_to (image_tag "mono-icons/search16.png", :alt=>"Voir"), model %> 
    <%= link_to model.name, {:controller => :aircrafts, :action =>:filter_aircrafts, :model=>model.id}, :remote =>true %>
    <br/>
  <% end %>
<% else %>
  <center>
    <%= image_tag "mono-icons/warning16.png" %> 
    <%= t(:no_model_found) %>
  </center>
<% end %>

app/views/aircrafts/edit.html.erb
<!-- breadcrumb -->
<% content_for :breadcrumb do %>
	<%= render :partial => "breadcrumb", :locals => {:action => "edit"} %>
<% end %>

<!-- unit system -->
<ul class="filter">
  <li><%= t(:actions) %></li>
  <li><%= link_to t(:show), aircraft_path(@aircraft) %></li>
  <li><%= link_to t(:show_model), model_path(@aircraft.model) %></li>
  <li class="desc"><%= t(:unit_system) %></li>
  <li id="si_unit" class="active"><%= t(:metric) %></li>
  <li id="us_unit" ><%= t(:us) %></li>
</ul>

<!-- header line user information -->
<h4 class="header-line"><%= t(:edit_aircraft) %></h4>
<p>
  <%= t(:new_aircraft_info) %> 
  <u><%= t(:save_aircraft) %></u> 
  <%= t(:to_finish) %>.
</p>

<div class="clear "></div>

<%= render 'form' %>

app/views/aircrafts/filter_aircrafts.js.erb
/* filters aircrafts by model */

$('#filtered_aircrafts').html("<%= escape_javascript(render(:partial => 'filtered_aircrafts')) %>");

app/views/aircrafts/fly.html.erb
<% content_for :breadcrumb do %>
	<%= render :partial => "breadcrumb", :locals => {:action => "fly"} %>
<% end %>

<% if user_signed_in? %>

<!-- actions -->
<ul class="filter">
  <li><%= t(:actions) %></li>
  <li><%= link_to t(:send_report), report_aircraft_path, :remote=>true %></li>
</ul>

<% end %>

<center>
  <p id="notice"><%= notice %></p>
</center>

<% if @units == "si" %>
  <% mass_unit = "[kg]" %>
  <% length_unit = "[m]" %>
  <% volume_unit = "[l]" %>
<% else %>
  <% mass_unit = "[lbs]" %>
  <% length_unit = "[in]" %>
  <% volume_unit = "[gal]" %>
<% end %>


<!-- header line user information -->
<h4 class="header-line"><%= @aircraft.callSign %></h4>
<p>
  <b><%= @aircraft.model.maker.name %> <%= @aircraft.model.name %></b>
  <br/>
  <%= l Date.today %>
</p>
<br/>
<div class="clear"></div>

<div class="one-half">
  
    <% if @errors.size > 0 %>
    <center>
      <p class="error"><b/><%= t(:error_found) %></b></p>
    </center>
    <% @errors.each_value do |error| %>
      <span class="error">
        - <%= error %>
      </span>
      <br/>
    <% end %>
  <% else %>
    <center>
      <p class="passed"><%= t(:no_error_found) %></p>
    </center>
  <% end %>
  
  <br/>
  
  <table id="wb-results">
    <!-- WEIGHTS -->
    <tr>
      <% if @errors["to_weight"] %>
        <td><%= image_tag "icons/exclamation.png"%></td>
      <% else %>
        <td><%= image_tag "icons/valid.png"%></td>
      <% end %>
      
      <td><%= t(:to_weight) %></td>
      <td><span class="static-mass"><%= @to_weight.round(2) %></span></td>
      
      <td><span class="mass-unit"><%= mass_unit %></span></td>
    </tr>
    <tr>
      <% if @errors["ld_weight"] %>
        <td><%= image_tag "icons/exclamation.png"%></td>
      <% else %>
        <td><%= image_tag "icons/valid.png"%></td>
      <% end %>
      
      <td><%= t(:ld_weight) %></td>
      <td><span class="static-mass"><%= @ld_weight.round(2) %></span></td>
      <td><span class="mass-unit"><%= mass_unit %></span></td>
    </tr>
    
    
    <!-- CG -->
    <tr>
      <% if @errors["to_cg"] %>
        <td><%= image_tag "icons/exclamation.png"%></td>
      <% else %>
        <td><%= image_tag "icons/valid.png"%></td>
      <% end %>
      
      <td><%= t(:to_cg) %></td>
      <td><span class="static-cg"><%= @to_cg.round(2) %></span></td>
      <td><span class="cg-unit"><%= length_unit %></span></td>
    </tr>
    <tr>
      <% if @errors["ld_cg"] %>
        <td><%= image_tag "icons/exclamation.png"%></td>
      <% else %>
        <td><%= image_tag "icons/valid.png"%></td>
      <% end %>
      
      <td><%= t(:ld_cg) %></td>
      <td><span class="static-cg"><%= @ld_cg.round(2) %></span></td>
      <td><span class="cg-unit"><%= length_unit %></span></td>
    </tr>
    
    <!-- FUEL -->
    <tr>
      <% if @errors["to_fuel"] %>
        <td><%= image_tag "icons/exclamation.png"%></td>
      <% else %>
        <td><%= image_tag "icons/valid.png"%></td>
      <% end %>
      
      <td><%= t(:to_fuel) %></td>
      <td><span class="static-volume"><%= @to_fuel.round(2) %></span></td>
      <td><span class="volume-unit"><%= volume_unit %></span></td>
    </tr>
    <tr>
      <% if @errors["ld_fuel"] %>
        <td><%= image_tag "icons/exclamation.png"%></td>
      <% else %>
        <td><%= image_tag "icons/valid.png"%></td>
      <% end %>
      
      <td><%= t(:ld_fuel) %></td>
      <td><span class="static-volume"><%= @ld_fuel.round(2) %></span></td>
      <td><span class="volume-unit"><%= volume_unit %></span></td>
    </tr>
    
    <% @stations.each_with_index do |station, n| %>
      <% if station.weightMax < @weights[n].to_f && station.weightMax > 0 %>
        <tr>
          <td><%= image_tag "icons/warning.png"%></td>
          <td>
            <% if I18n.locale == :fr %>
              <%= station.station_type.fr %>
            <% else %>
              <%= station.station_type.en %>
            <% end %>
            (max. <span class="static-mass"><%= station.weightMax %></span>)
          </td>
          <td><span class="static-mass"><%= @weights[n].to_f.round(2) %></span></td>
          <td><span class="mass-unit"><%= mass_unit %></span></td>
        </tr>
      <% end %>
    <% end %>
  </table> 
</div>


<div class="one-half last">
  <%= render :partial => "enveloppe_drawing"%>
</div>

<div class="clear"></div>

<br/>
<br/>
<br/>

<p>
  <center>
    <%= image_tag "mono-icons/warning16.png" %> <b><%= t(:info_only_warning) %></b>
  </center>
</p>


<!-- comments -->
<%= render :partial => "shared/comments", :locals => {:allow_reply => :yes} %>

app/views/aircrafts/index.html.erb
<!-- breadcrumb -->
<% content_for :breadcrumb do %>
	<%= render :partial => "breadcrumb", :locals => {:action => "index"} %>
<% end %>

<!-- page information -->
<h4 class="header-line"><%= t(:browse_all_aircrafts) %></h4>
<p>
  <%= t(:search_aircraft_info1) %>
  <%= t(:search_aircraft_click) %> 
  <%= image_tag "mono-icons/search16.png" %> 
  <%= t(:to_show_details) %>
  <%= t(:and) %> 
  <%= image_tag "mono-icons/risegraph16.png" %> 
  <%= t(:to_do_weight_balance) %>. 
  <%= t(:add_if_cannot_find) %>
  <%= image_tag "mono-icons/plus16.png" %> 
  <%= t(:to_add_it) %>.
</p>

<div class="clear "></div>
<br/>
<!-- lists all makers -->
<div class="one-third">
  <div class="rounded-centered">
    
    <h5><%= image_tag "icons/wrench.png" %> <%= t(:makers) %></h5>
    <div class="rounder_center_underline"><%= image_tag "shadow-1-3.png" %> </div>
    
    <div id="filtered_makers">
    
      <div class="options">
        <%= link_to image_tag("mono-icons/plus16.png"), new_maker_path %>  
      </div>
      
      <center><h6><%= link_to t(:all_makers), aircrafts_path %></h6></center>
      <br/>
      
      <% @makers.each do |maker| %>
        <%= link_to (image_tag "mono-icons/search16.png", :alt=>"Voir"), maker %> 
        <%= link_to maker.name, {:controller => :aircrafts, :action =>:filter_models, :maker=>maker.id}, :remote=>true %>
        <br/>
      <% end %>
    </div>
  </div>
</div>

<!-- lists models filtered by maker -->
<div class="one-third">
  <div class="rounded-centered">
    
    <h5><%= image_tag "icons/tag.png" %> <%= t(:models) %></h5>
    <div class="rounder_center_underline"><%= image_tag "shadow-1-3.png" %> </div>
    
    <div id="filtered_models">  
      <center><h6><%= t(:all_models) %></h6></center>
      <br/>
    
      <% @models.each do |model| %>
        <%= link_to (image_tag "mono-icons/search16.png", :alt=>"Voir"), model %> 
        <%= link_to model.name, {:controller => :aircrafts, :action =>:filter_aircrafts, :model=>model.id}, :remote =>true %><br/>
      <% end %>
    </div>
    
  </div>
</div>

<!-- lists aircrafts filtered by models -->
<div class="one-third">
  <div class="rounded-centered">
    
    <h5><%= image_tag "icons/airplane.png" %> <%= t(:aircrafts) %></h5>
    <div class="rounder_center_underline"><%= image_tag "shadow-1-3.png" %> </div>
    
    <div id="filtered_aircrafts">
      <center><h6><%= t(:all_aircrafts) %></h6></center>
      <br/>
      
      <% @aircrafts.each do |craft| %>
        <%= link_to (image_tag "mono-icons/risegraph16.png", :alt=>"Editer"), weight_balance_aircraft_path(:id =>craft.id) %> 
        <%= link_to craft.callSign, craft %><br/>
      <% end %>
    </div>
    
  </div>
</div>

<div class="clear "></div>