config/routes.rb
Www::Application.routes.draw do
  
  scope "(:locale)", :locale => /en|fr/ do
    
    match 'home'    => "static_pages#home",   :as => 'home',    :via => :get
    match 'admin'   => "static_pages#admin",  :as => 'admin',   :via => :get
    match 'mobile'  => "static_pages#mobile", :as => 'mobile',  :via => :get
    match 'faq'     => "static_pages#faq",    :as => 'faq',     :via => :get
    match 'contact' => 'contact#new',         :as => 'contact', :via => :get
    match 'contact' => 'contact#create',      :as => 'contact', :via => :post
    
    match 'all_aircrafts'      => 'aircrafts#all_aircrafts',            :as=>"all_aircrafts",       :via =>:get
    match 'all_models'         => 'models#all_models',                  :as=>"all_models",          :via =>:get
    match 'all_makers'         => 'makers#all_makers',                  :as=>"all_makers",          :via =>:get
    match 'all_station_types'  => 'station_types#all_station_types',    :as=>"all_station_types",   :via =>:get
    match 'all_fuel_locations' => 'fuel_locations#all_fuel_locations',  :as=>"all_fuel_locations",  :via =>:get
    match 'all_fuel_types'     => 'fuel_types#all_fuel_types',          :as=>"all_fuel_types",      :via =>:get
    
    resources :makers,          :except => [:index]
    resources :models,          :except => [:index]
    resources :envelopes,       :except => [:index]
    resources :fuel_types,      :except => [:show] 
    resources :fuel_locations,  :except => [:show]
    resources :station_types,   :except => [:show]
    
    devise_for :users
      
    resources :users do
      member do
        put :save_roles
        get :edit_roles
        get :profile
      end
    end
    
    resources :aircrafts do
      
      resources :aircraft_comments, :except =>[:index, :new]
      
      collection do 
        get :filter_models
        get :filter_aircrafts
      end
      
      member do 
        get :clone
        get :weight_balance
        get :fly  
        get :report    
      end 
      
    end
    
    resources :aircraft_comments, :except => [:new]
    
    root :to => "static_pages#home"
  end
  

end

app/controllers/fuel_types_controller.rb
class FuelTypesController < ApplicationController
  
  ## user authentication
  before_filter :authenticate_user!, :except=>[:all_fuel_types]
  
    ### REST API specific methods ##################################################
  
  def all_fuel_types
    @fuel_types = FuelType.all
    
    respond_to do |format|
      format.json{ render :json => @fuel_types}
    end 
  end
  
  ### HTML + JSON REST ##################################################

  
  # GET /fuel_types
  # GET /fuel_types.json
  def index
    @fuel_types = FuelType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @fuel_types }
    end
  end

  # GET /fuel_types/1
  # GET /fuel_types/1.json
  def show
    @fuel_type = FuelType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @fuel_type }
    end
  end

  # GET /fuel_types/new
  # GET /fuel_types/new.json
  def new
    @fuel_type = FuelType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @fuel_type }
    end
  end

  # GET /fuel_types/1/edit
  def edit
    @fuel_type = FuelType.find(params[:id])
  end

  # POST /fuel_types
  # POST /fuel_types.json
  def create
    @fuel_type = FuelType.new(params[:fuel_type])

    respond_to do |format|
      if @fuel_type.save
        format.html { redirect_to fuel_types_path, :notice => 'Fuel type was successfully created.' }
        format.json { render :json => @fuel_type, :status => :created, :location => @fuel_type }
      else
        format.html { render :action => "new" }
        format.json { render :json => @fuel_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /fuel_types/1
  # PUT /fuel_types/1.json
  def update
    @fuel_type = FuelType.find(params[:id])

    respond_to do |format|
      if @fuel_type.update_attributes(params[:fuel_type])
        format.html { redirect_to fuel_types_path, :notice => 'Fuel type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @fuel_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /fuel_types/1
  # DELETE /fuel_types/1.json
  def destroy
    @fuel_type = FuelType.find(params[:id])
    @fuel_type.destroy

    respond_to do |format|
      format.html { redirect_to fuel_types_path }
      format.json { head :no_content }
    end
  end
end

app/helpers/fuel_types_helper.rb
module FuelTypesHelper
end

app/views/fuel_types/_access_denied.html.erb
<br>
<br>
<center>
  <h1><%= t(:restricted_content) %></h1>
  <br/>
  <%= link_to t(:back_home), home_path %>
</center>

app/views/fuel_types/_breadcrumb.html.erb
<% if action.eql?("index") %>
	<%= link_to t(:home), home_path %>
	<%= link_to t(:administration), admin_path %>
  <%= t(:fuel_types) %>
<% end %>

<% if action.eql?("new") %>
	<%= link_to t(:home), home_path %>
	<%= link_to t(:administration), admin_path %>
	<%= link_to t(:fuel_types), fuel_types_path %>
  <%= t(:new) %>
<% end %>

<% if action.eql?("show") %>
	<%= link_to t(:home), home_path %>
	<%= link_to t(:administration), admin_path %>
	<%= link_to t(:fuel_types), fuel_types_path %>
  <%= @fuel_type.name %>
<% end %>

app/views/fuel_types/_form.html.erb
<%= form_for(@fuel_type) do |f| %>
  <% if @fuel_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fuel_type.errors.count, "error") %> prohibited this fuel_type from being saved:</h2>

      <ul>
      <% @fuel_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label t(:name) %><br />
    <%= f.text_field :name, :class=>"textInput"%>
  </div>
  <div class="field">
    <%= f.label t(:density) %> [kg/l]<br />
    <%= f.text_field :density, :class=>"textInput" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fuel_types/edit.html.erb
<% if can? :manage, @fuel_type %>

<!-- breadcrumb -->
<% content_for :breadcrumb do %>
	<%= render :partial => "breadcrumb", :locals => {:action => "edit"} %>
<% end %>

<!-- actions -->
<ul class="filter">
  <li><%= t(:actions) %></li>
  <li><%= link_to t(:back), fuel_types_path %></li>
  <li><%= link_to t(:delete), @fuel_type, :confirm => 'Are you sure?', :method => :delete %></li>
</ul>

<!-- page information -->
<h4 class="header-line"><%= t(:fuel_type) %></h4>
<p>
  <%= t(:fuel_edit_info) %>
</p>
<div class="clear "></div>

<br/>

<div id="centered-form">
  <div class="rounded-centered">
    <%= render 'form' %>
  </div>
</div>

<% else %>
  <%= render :partial => "access_denied" %>
<% end %>

app/views/fuel_types/index.html.erb
<% if can? :manage, @fuel_types %>

<!-- breadcrumb -->
<% content_for :breadcrumb do %>
	<%= render :partial => "breadcrumb", :locals => {:action => "index"} %>
<% end %>

<!-- actions -->
<ul class="filter">
  <li><%= t(:actions) %></li>
  <li><%= link_to t(:new_fuel_type), new_fuel_type_path %></li>
</ul>

<!-- page information -->
<h4 class="header-line"><%= t(:cat_fuel_types) %></h4>
<p>
  <%= t(:fuel_index_info) %>
</p>
<div class="clear "></div>

<br/>

<div class="center-smaller-bordered">
  <table  class="bordered">
    <tr>
      <th><%= t(:name) %></th>
      <th><%= t(:density) %> [kg/l]</th>
    </tr>
  
  <% @fuel_types.each do |fuel_type| %>
    <tr>
      <td class="centered-text"><%= link_to fuel_type.name, edit_fuel_type_path(fuel_type) %></td>
      <td class="centered-text"><%= fuel_type.density %></td>  
    </tr>
  <% end %>
  </table>
</div>

<% else %>
  <%= render :partial => "access_denied" %>
<% end %>

app/views/fuel_types/new.html.erb
<% if can? :manage, @fuel_type %>
<!-- breadcrumb -->
<% content_for :breadcrumb do %>
	<%= render :partial => "breadcrumb", :locals => {:action => "new"} %>
<% end %>


<!-- actions -->
<ul class="filter">
  <li><%= t(:actions) %></li>
  <li><%= link_to 'Back', fuel_types_path %></li>
</ul>

<!-- page information -->
<h4 class="header-line"><%= t(:fuel_type) %></h4>
<p>
  <%= t(:fuel_edit_info) %>
</p>
<div class="clear "></div>

<br/>

<div id="centered-form">
  <div class="rounded-centered">
    <%= render 'form' %>
  </div>
</div>

<% else %>
  <%= render :partial => "access_denied" %>
<% end %>

app/views/fuel_types/show.html.erb
<% if can? :manage, @fuel_type %>

<!-- breadcrumb -->
<% content_for :breadcrumb do %>
	<%= render :partial => "breadcrumb", :locals => {:action => "show"} %>
<% end %>

<!-- actions -->
<ul class="filter">
  <li><%= t(:actions) %></li>
  <li><%= link_to 'Edit', edit_fuel_type_path(@fuel_type) %></li>
  <li><%= link_to 'Back', fuel_types_path %></li>
</ul>

<p id="notice"><%= notice %></p>

<!-- page information -->
<h4 class="header-line">Fuel type information</h4>
<div class="clear "></div>

<br/>


<p>
  <b>Name:</b>
  <%= @fuel_type.name %>
</p>

<p>
  <b>Density :</b>
  <%= @fuel_type.density %> [kg/l]
</p>

<% else %>
  <h1>Not authorized</h1>
<% end %>