config/routes.rb
Www::Application.routes.draw do
  
  scope "(:locale)", :locale => /en|fr/ do
    
    match 'home'    => "static_pages#home",   :as => 'home',    :via => :get
    match 'admin'   => "static_pages#admin",  :as => 'admin',   :via => :get
    match 'mobile'  => "static_pages#mobile", :as => 'mobile',  :via => :get
    match 'faq'     => "static_pages#faq",    :as => 'faq',     :via => :get
    match 'contact' => 'contact#new',         :as => 'contact', :via => :get
    match 'contact' => 'contact#create',      :as => 'contact', :via => :post
    
    match 'all_aircrafts'      => 'aircrafts#all_aircrafts',            :as=>"all_aircrafts",       :via =>:get
    match 'all_models'         => 'models#all_models',                  :as=>"all_models",          :via =>:get
    match 'all_makers'         => 'makers#all_makers',                  :as=>"all_makers",          :via =>:get
    match 'all_station_types'  => 'station_types#all_station_types',    :as=>"all_station_types",   :via =>:get
    match 'all_fuel_locations' => 'fuel_locations#all_fuel_locations',  :as=>"all_fuel_locations",  :via =>:get
    match 'all_fuel_types'     => 'fuel_types#all_fuel_types',          :as=>"all_fuel_types",      :via =>:get
    
    resources :makers,          :except => [:index]
    resources :models,          :except => [:index]
    resources :envelopes,       :except => [:index]
    resources :fuel_types,      :except => [:show] 
    resources :fuel_locations,  :except => [:show]
    resources :station_types,   :except => [:show]
    
    devise_for :users
      
    resources :users do
      member do
        put :save_roles
        get :edit_roles
        get :profile
      end
    end
    
    resources :aircrafts do
      
      resources :aircraft_comments, :except =>[:index, :new]
      
      collection do 
        get :filter_models
        get :filter_aircrafts
      end
      
      member do 
        get :clone
        get :weight_balance
        get :fly  
        get :report    
      end 
      
    end
    
    resources :aircraft_comments, :except => [:new]
    
    root :to => "static_pages#home"
  end
  

end

app/models/role.rb
class Role < ActiveRecord::Base

  ## associations
  has_and_belongs_to_many :users
  
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  
  ## user authentication
  before_filter :authenticate_user!
  
  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @roles }
    end
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
    @role = Role.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @role }
    end
  end

  # GET /roles/new
  # GET /roles/new.json
  def new
    @role = Role.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @role }
    end
  end

  # GET /roles/1/edit
  def edit
    @role = Role.find(params[:id])
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(params[:role])

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, :notice => 'Role was successfully created.' }
        format.json { render :json => @role, :status => :created, :location => @role }
      else
        format.html { render :action => "new" }
        format.json { render :json => @role.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /roles/1
  # PUT /roles/1.json
  def update
    @role = Role.find(params[:id])

    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to @role, :notice => 'Role was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @role.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    respond_to do |format|
      format.html { redirect_to roles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_access_denied.html.erb
<br>
<br>
<center>
  <h1><%= t(:restricted_content) %></h1>
  <br/>
  <%= link_to t(:back_home), home_path %>
</center>

app/views/roles/_breadcrumb.html.erb
<% if action.eql?("index") %>
	<%= link_to t(:home), home_path %>
	<%= link_to t(:administration), admin_path %>
  <%= t(:cat_users) %>
<% end %>

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<!-- breadcrumb -->
<% content_for :breadcrumb do %>
  <%= link_to t(:home), "" %>
	<%= link_to "Administration", :controller=>:static_pages, :action=>:admin %>
	Roles
<% end %>

<h1>Editing role</h1>

<%= render 'form' %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<!-- breadcrumb -->
<% content_for :breadcrumb do %>
  <%= link_to t(:home), "" %>
	<%= link_to "Administration", :controller=>:static_pages, :action=>:admin %>
	Roles
<% end %>

<h1>Listing roles</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @roles.each do |role| %>
  <tr>
    <td><%= role.name %></td>
    <td><%= link_to 'Show', role %></td>
    <td><%= link_to 'Edit', edit_role_path(role) %></td>
    <td><%= link_to 'Destroy', role, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Role', new_role_path %>

app/views/roles/new.html.erb
<!-- breadcrumb -->
<% content_for :breadcrumb do %>
  <%= link_to t(:home), "" %>
	<%= link_to "Administration", :controller=>:static_pages, :action=>:admin %>
	Roles
<% end %>

<h1>New role</h1>

<%= render 'form' %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<!-- breadcrumb -->
<% content_for :breadcrumb do %>
  <%= link_to t(:home), "" %>
	<%= link_to "Administration", :controller=>:static_pages, :action=>:admin %>
	Roles
<% end %>

<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @role.name %>
</p>


<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>